### PR TITLE
Add H2 mapping for purl property

### LINKED ISSUE #290: Add H2 mapping for purl

### PR DESCRIPTION
**Pull request by arcadiafalcone**
**NOTE:  Person merging should ensure that any mapping changes are ticketed as a cocina mapping in dor-services-app, e.g. dor-services-app/issues/1251**

## Why was this change made?
Closes #290

### CODE REVIEW

**Review by ndushay — CHANGES_REQUESTED** [review]
would it make sense for this to have a little more context?   That is ... it's a key value pair ... but where would it go in a relevant cocina model ?

**Comment by arcadiafalcone** [comment]
It's a top-level property - would it be helpful to include a title property as well to position it more clearly in the data structure?

**Comment by ndushay** [comment]
yes - maybe ADDING an example with it with something else would help.

**Review by ndushay — APPROVED** [review]

**Comment by ndushay** [comment]
I made no ticket in DSA;  if this is top priority, perhaps you can make the dsa ticket.  This file is noted in the alignment work, tho.

**Pull request merged**
