### PR TITLE
Fix namePart type to use termsOfAddress

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by arcadiafalcone — CHANGES_REQUESTED** [review]
It should be "term of address" singular, but other than that this is fine.

**Comment by jcoyne** [comment]
@arcadiafalcone I'm not sure what you are suggesting. I've changed it to `termsOfAddress` which is what is in the MODS documentation. https://www.loc.gov/standards/mods/userguide/name.html

**Comment by arcadiafalcone** [comment]
I meant it should be "term of address" on the COCINA side.

**Comment by jcoyne** [comment]
@arcadiafalcone here? https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/2deb64477f4a3132b39a2f150bb2948e5600fcec/mods_cocina_mappings/mods_to_cocina_name.txt#L94

**Review by arcadiafalcone — APPROVED** [review]

**Pull request merged**
