### PR TITLE
Update h2_to_cocina_contributor.txt

### PR DESCRIPTION
**Pull request by ndushay**
Add status=primary to Funder example for h2_to_cocina_contributor mappings

### CODE REVIEW

**Comment by jcoyne** [comment]
Can you help me understand why this change is needed?

**Comment by ndushay** [comment]
@jcoyne it's needed because @arcadiafalcone and I spoke about it and this makes this example consistent with the other examples.

**Comment by jcoyne** [comment]
@ndushay how will the user of H2 designate a primary contributor?

**Comment by ndushay** [comment]
@jcoyne per Arcadia's instructions:  https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/h2_cocina_mappings/h2_to_cocina_contributor.txt#L4

**Review by arcadiafalcone — APPROVED** [review]

**Pull request merged**
